# Change these first
owner: elepallec-th # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CRL v4
    url: http://crl.pki.thalesgroup.com
  - name: Identity Provider
    url: https://sso-idp.thalesgroup.com
    expectedStatusCodes:
      - 404
  - name: Single-Sign On
    url: https://websso.online.thalesgroup.com/login/websso_login_unique.pl
  - name: ADFS
    url: https://login.sso.thalesgroup.com/adfs/.well-known/openid-configuration
  - name: CRL HTTP Port
    check: "tcp-ping"
    url: 192.54.144.100
    port: 80
  - name: SSO HTTPS Port
    check: "tcp-ping"
    url: 192.54.144.12
    port: 443
  - name: IdP HTTPS Port
    check: "tcp-ping"
    url: 192.54.144.69
    port: 443
  - name: ADFS HTTPS Port
    check: "tcp-ping"
    url: 192.54.144.68
    port: 443


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Quick personal monitoring with **Upptime**"
  introMessage: Monitor some public URLs
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
