# Change these first
owner: elepallec-th # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Thales CRL
    url: http://crl.thalesgroup.com
  - name: Thales Identity Provider
    url: https://sso-idp.thalesgroup.com
  - name: Thales SSO
    url: https://websso.online.thalesgroup.com/login/websso_login_unique.pl
  - name: SSO HTTPS Port
    check: "tcp-ping"
    url: 192.54.144.12
  - name: IdP HTTPS Port
    check: "tcp-ping"
    url: 192.54.144.69
    port: 443
  - name: DDM
    url: https://ddm.online.thalesgroup.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Quick personal monitoring with **Upptime**
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
